api/urls.py
from django.conf.urls import patterns, include, url
from rest_framework import routers
from api import views


router = routers.DefaultRouter()
urlpatterns = patterns('',
                       url(r'^', include(router.urls)),
                       url(r'^user_visits', views.parse_user_visit),
                       )

auth/urls.py
from django.conf.urls import patterns, url

from auth.views import auth_login, auth_logout, auth_passcode_login

urlpatterns = patterns('',
                       url(r'^login/$', auth_login, name='login'),
                       url(r'^passcode/$',
                           auth_passcode_login,
                           name='passcode'),
                       url(r'^logout/$', auth_logout, name='logout'))

cemetaryar/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.template.loader import add_to_builtins
from rest_framework import routers

from django.contrib import admin
admin.autodiscover()
add_to_builtins('django.templatetags.i18n')

urlpatterns = patterns(
    '',
    url(r'^', include('channel.urls', namespace="channel")),
    url(r'^', include('api.urls', namespace="api")),
    url(r'^auth/', include('auth.urls', namespace="auth")),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^api-auth/', include('rest_framework.urls',
                               namespace='rest_framework')),
    ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

channel/urls.py
from django.conf.urls import patterns, url

from channel.views import AddLocation, EditLocation
from channel import views


urlpatterns = patterns(
    '',
    url(r'^channel/(?P<channel_id>\d+)/add/$',
        AddLocation.as_view(), name='add_location'),
    url(r'^$', views.index, name='index'),
    url(r'^channel/(?P<channel_id>\d+)/$',
        views.detail, name='detail'),
    url(r'^channel/(?P<channel_id>\d+)/view/$',
        views.view_locations, name='view'),
    url(r'^channel/(?P<channel_id>\d+)/remove/(?P<location_id>\d+)/$',
        views.remove_location, name='remove_location'),
    url(r'^channel/(?P<channel_id>\d+)/edit/(?P<location_id>\d+)/$',
        EditLocation.as_view(), name='edit_location'),
    url(r'^channel/(?P<channel_id>\d+)/edit/$',
        views.edit_channel, name='edit_channel'),
    url(r'^channel/(?P<channel_id>\d+)/map/(?P<latitude>(-?\d+\.\d+)),(?P<longitude>(-?\d+\.\d+)),(?P<radius>(-?\d+))/$',
        views.update_map, name='update_map'),)

templates/base.html
{% load i18n %}
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

<link rel="stylesheet" href="{% static 'channel/style.css' %}?{% now "U" %}">

{% if fullscreen %}
<meta http-equiv="Refresh" content="120">
<link rel="stylesheet" href="{% static 'channel/fullscreen_style.css' %}">
{% endif %}

{% block css %}{% endblock %}

{% comment %}Translators: Site title{% endcomment %}
<title>{% block title %}{% blocktrans %}LOCI - Location Oriented Community Interface{% endblocktrans %}{% endblock %}</title>
</head>


<body>

{% block header %}

	<header>
		<div class="container">
			<div class="row">

				<div class="col-sm-12">
				{% block header_title %}

				<h2 class="pull-right header">
				<form action="{% url 'set_language' %}" method="post">
					{% csrf_token %}
					<input name="next" type="hidden" value="{{ redirect_to }}" />
					<select class="form-control bfh-languages" name="language" onchange="this.form.submit();">
					<option value=''></option>
					{% for language in AVAILABLE_LANGUAGES%}
						<option value="{{ language.0 }}" {% if language.0 == LANGUAGE_CODE %} selected="selected"{% endif %}> {{ language.1 }}</option>
					{% endfor %}
					</select>
				</form>
				</h2>
				<div class="title-text">
				<h2 class="pull-left  image-left header"><img src='{% static "images/mesch_white.png" %}' /></h2>
					{% if user.is_authenticated %}
						<h2 class="pull-left header"><a href="{% url 'channel:index' %}">
							<i class="fa fa-tree fa-fw"></i> {% trans "Home" %}</a>
							{% if channel %}
								<span class="channel-name"> | {{ channel }}</span>
							{% endif %}
							{% if channel and user.is_staff %}
								<span class="bar-spacer">  &nbsp;| </span>
								<a href="{% url 'channel:edit_channel' channel.id %}">{% trans "Channel Settings" %} </a>
							{% endif %}
							<span class="bar-spacer">  &nbsp;| </span>
							<a href="{% url 'auth:logout' %}">{% trans "Logout" %} </a>
						</h2>
					{% else %}
						<h2 class="pull-left header"><a href="{% url 'channel:index' %}">
							<i class="fa fa-home fa-fw"></i> {% trans "Home" %}</a>
							<span class="bar-spacer">|</span>
							<!-- <a href="{% url 'auth:login' %}"><i class="fa fa-key fa-fw"></i>
							{% trans "Login" %}</a><span class="bar-spacer"> | </span> -->
							<a href="{% url 'auth:passcode' %}">
							<i class="fa fa-key fa-fw"></i> {% trans "Passcode Login" %}</a>
						</h2>
					{% endif %}
				</div>
				{% endblock %}
				</div>
			</div>
		</div>
	</header>

{% endblock %}




{% block container %}

	<main>
		<form action="{% block action %}{% endblock %}" method="{% block method %}{% endblock %}" enctype="multipart/form-data">
			<div class="container main">
				<div class="row">
					<div class="col-sm-12">
						{% block pagetitle %}{% endblock %}
					</div>
				</div>
				<div class="row">
					<div class="col-sm-12">
						{% block main-content %}{% endblock  %}
					</div>
				</div>
			</div>
		</form>
	</main>

{% endblock %}

{% block footer %}
	<footer>
		<div class="container footer">
			<div class="row">
				<p class="text-muted">meSch receives funding from the European Community's 7FP ICT for access to cultural resources GA 600851.
				<br/>{% trans "Copyright &copy; meSch Project 2015" %}</p>
			</div>
		</div>
    </footer>
{% endblock %}
<script type="text/javascript" src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false&amp;language=en"></script>
<script type="text/javascript" src="{% static 'channel/gmap3.min.js' %}"></script>
{% if not IS_DEVELOPMENT %}
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-61589810-1', 'auto');
  ga('send', 'pageview');

</script>
{% endif %}
{% block scripts %}{% endblock %}
<script type="text/javascript">
	{% block js %}{% endblock %}
</script>

</body>

</html>