api/urls.py
from django.conf.urls import patterns, include, url
from rest_framework import routers
from api import views


router = routers.DefaultRouter()
urlpatterns = patterns('',
                       url(r'^', include(router.urls)),
                       url(r'^user_visits', views.parse_user_visit),
                       )

cemetaryar/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.template.loader import add_to_builtins
from rest_framework import routers

from django.contrib import admin
admin.autodiscover()
add_to_builtins('django.templatetags.i18n')

urlpatterns = patterns(
    '',
    url(r'^', include('channel.urls', namespace="channel")),
    url(r'^', include('api.urls', namespace="api")),
    url(r'^auth/', include('auth.urls', namespace="auth")),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^api-auth/', include('rest_framework.urls',
                               namespace='rest_framework')),
    ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

channel/urls.py
from django.conf.urls import patterns, url

from channel.views import AddLocation, EditLocation
from channel import views


urlpatterns = patterns(
    '',
    url(r'^channel/(?P<channel_id>\d+)/add/$',
        AddLocation.as_view(), name='add_location'),
    url(r'^$', views.index, name='index'),
    url(r'^channel/(?P<channel_id>\d+)/$',
        views.detail, name='detail'),
    url(r'^channel/(?P<channel_id>\d+)/view/$',
        views.view_locations, name='view'),
    url(r'^channel/(?P<channel_id>\d+)/remove/(?P<location_id>\d+)/$',
        views.remove_location, name='remove_location'),
    url(r'^channel/(?P<channel_id>\d+)/edit/(?P<location_id>\d+)/$',
        EditLocation.as_view(), name='edit_location'),
    url(r'^channel/(?P<channel_id>\d+)/edit/$',
        views.edit_channel, name='edit_channel'),
    url(r'^channel/(?P<channel_id>\d+)/map/(?P<latitude>(-?\d+\.\d+)),(?P<longitude>(-?\d+\.\d+)),(?P<radius>(-?\d+))/$',
        views.update_map, name='update_map'),)

channel/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
import sys
import os
from django.conf import settings
from django.dispatch import receiver
from django.template import defaultfilters
from django.utils.translation import ugettext_lazy as _
import datetime
from django.utils import timezone


# Apparently there is a naming conflict with magic in IOS which the
# package owners are both too stubborn to fix - so attempt work around
try:
    import magic
    if not hasattr(magic, 'from_buffer'):
        import imp
        magic = imp.load_source('magic', settings.PYTHON_MAGIC_PATH)
except ImportError:
    print >> sys.stderr, "No magic module available."


# The FileField content-type is supplied by browser therefore not a
# reliable way to get the mimetime. We must therefore check the file
# using magic. 'trust but verify'
def validate_mime(value):
    try:
        mime = magic.from_buffer(value.read(1024), mime=True)
        if mime not in settings.ALLOWED_UPLOAD_EXTENSIONS:
            raise ValidationError(
                _('File %(type)s not supported. Filetypes allowed: ')
                % {'type': value} +
                ', ' .
                join(settings.ALLOWED_UPLOAD_EXTENSIONS))
    except AttributeError as e:
        raise ValidationError(
            _('This file-type could not be validated for file %(type)s '
              % {'type': value}))


def validate_size(value):
    try:
        if value.size > settings.MAX_UPLOAD_SIZE:
                raise ValidationError(
                    _('Please keep filesize under %(max_size)s. Current filesize %(current_size)s.')
                    % {'max_size': defaultfilters.filesizeformat(settings.MAX_UPLOAD_SIZE),
                       'current_size': defaultfilters.filesizeformat(value.size)})
    except AttributeError as e:
        raise ValidationError(
            _('Please keep filesize under %(max_size)s. Current filesize %(current_size)s.')
            % {'max_size': defaultfilters.filesizeformat(settings.MAX_UPLOAD_SIZE),
                'current_size': defaultfilters.filesizeformat(value.size)})


class Channel(models.Model):

    title = models.CharField(_("Title"), max_length=20)
    description = models.CharField(_("Description"),
                                   max_length=140,
                                   blank=True)
    centre_latitude = models.FloatField(_("Latitude"))
    centre_longitude = models.FloatField(_("Longitude"))
    radius = models.IntegerField(_("Radius"), blank=True, null=True)

    def __unicode__(self):
        return self.title


class Location(models.Model):
    file = models.FileField(upload_to='.',
                            validators=[validate_mime, validate_size],
                            blank=True, null=True)
    title = models.CharField(_("Title"), max_length=80)
    latitude = models.FloatField(_("Latitude"))
    longitude = models.FloatField(_("Longitude"))
    description = models.TextField(_("Description"), max_length=250)
    name = models.CharField(_("Description"), max_length=150, blank=True, null=True)
    channel = models.ForeignKey(Channel,
                                blank=True,
                                null=True,
                                verbose_name=_('Channel'))
    md5 = models.CharField(max_length=32, blank=True, null=True)
    file_type = models.CharField(max_length=32, blank=True, null=True)
    is_fixed = models.BooleanField(default=False)
    language_code = models.CharField(max_length=5,
                                     default=settings.LANGUAGE_CODE.lower(),
                                     choices=settings.LANGUAGES)

    updated = models.DateTimeField(
        default=timezone.make_aware(datetime.datetime.today(),
                                    timezone.get_current_timezone()))
    updated_by = models.ForeignKey(User)

    def __unicode__(self):
        return self.title


# Auto-delete files from filesystem when Location deleted from database
@receiver(models.signals.post_delete, sender=Location)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """Deletes file from filesystem
    when corresponding 'Location' object is deleted.
    """
    if instance.file:
        if os.path.isfile(instance.file.path):
            os.remove(instance.file.path)


# Auto-delete files from filesystem when Location file changed
@receiver(models.signals.pre_save, sender=Location)
def auto_delete_file_on_change(sender, instance, **kwargs):
    """Deletes file from filesystem
    when corresponding `Location` object is changed.
    """
    if not instance.pk:
        return False

    try:
        old_file = Location.objects.get(pk=instance.pk).file
    except Location.DoesNotExist:
        return False

    new_file = instance.file
    if old_file and not old_file == new_file:
        if os.path.isfile(old_file.path):
            os.remove(old_file.path)
        return False


class LocationLog(models.Model):
    LOGTYPES = (
        ('c', 'created'),
        ('e', 'edited'),
        ('d', 'deleted'),
    )

    date = models.DateTimeField(
        default=timezone.make_aware(datetime.datetime.today(),
                                    timezone.get_current_timezone()))
    user = models.ForeignKey(User)
    # Do not use foreign key to store Location as system will
    # delete LogLocation when Location object is deleted
    location_id = models.IntegerField()
    type = models.CharField(max_length=1, choices=LOGTYPES)

channel/views.py
import hashlib
import logging
import sys
import os
import datetime
from itertools import chain

from django.shortcuts import render, render_to_response
from django.http import Http404, HttpResponseRedirect, HttpResponse, HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.views.generic import FormView, UpdateView
from django.utils.decorators import method_decorator
from django.utils import timezone

from channel.models import Channel, Location, LocationLog
from channel.forms import ChannelForm, LocationForm

from api.utils import get_locations

from django.utils import translation


# If the user is authenticated list all channels and provide add new channel
# form. If the form is POSTed then add the new channel to the database
# (if no errors).
def index(request):
    # If only one channel allowed - default to this
    if(settings.SINGLE_MAIN_CHANNEL_ID):
        return HttpResponseRedirect('/channel/%s/'
                                    % settings.SINGLE_MAIN_CHANNEL_ID)

    if request.method == 'POST':
        form = ChannelForm(request.POST)
        if form.is_valid():
            new_channel = form.save()
            return HttpResponseRedirect('/')
        else:
            all_channels = Channel.objects.all().order_by('title')
            context = {
                'form': form,
                'channels': all_channels,
            }
    else:
        all_channels = Channel.objects.all().order_by('title')
        form = ChannelForm()
        context = {
            'channels': all_channels,
            'form': form,
        }

    return render(request, 'channel/channel.html', context)


# Load the channel and query all (non-fixed) locations associated
# with that channel to pass to template. Pass a form to add new locations.
def detail(request, channel_id):
    try:
        channel = Channel.objects.get(pk=channel_id)
        locations = get_locations(request.user.username,
                                  channel,
                                  request.LANGUAGE_CODE)

        # Only allow fullscreen for logged out users
        fullscreen = None
        if request.GET.get('fullscreen') == '1' and \
                not request.user.is_authenticated():
            fullscreen = request.GET.get('fullscreen', '')
            request.session['django_language'] = 'nl-nl'

        form = LocationForm()
        context = {
            'locations': locations,
            'channel': channel,
            'form': form,
            'fullscreen': fullscreen
        }
    except Exception as e:
        raise

    return render(request, 'channel/detail.html', context)


# Query all locations for the channel to list in the template.
@login_required
def view_locations(request, channel_id):
    channel = Channel.objects.get(pk=channel_id)

    if request.user.is_staff:
        # On edit page view all non fixed locations
        locations = Location.objects.filter(channel=channel)
        locations = locations.filter(is_fixed=0).order_by('-id')
        if locations:
            context = {
                'locations': locations,
                'channel': channel,
            }

        return render(request, 'channel/view_locations.html', context)

    # User is not staff or have no locations
    return HttpResponseRedirect('/channel/%s/' % channel.id)


# Refresh the map using the channel, lat and long passed in to
# determine the center.
def update_map(request, channel_id, latitude, longitude, radius):
    channel = Channel.objects.get(pk=channel_id)
    locations = get_locations(request.user.username,
                              channel,
                              request.LANGUAGE_CODE)

    context = {
        'locations': locations,
        'channel': channel,
        'latitude': latitude,
        'longitude': longitude,
        'radius': radius,
    }

    return render(request, 'channel/map.html', context)


class AddLocation(FormView):
    form_class = LocationForm
    template_name = 'channel/location_form.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(AddLocation, self).dispatch(*args, **kwargs)

    # handle case where have submitted a form
    # gotten an error, the error is shown with the map detail below
    # and for some reason the user refreshes the page ..
    # redirect back to detail page with no form and no form error messages
    def get(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        context = self.get_context_data(**kwargs)
        context['form'] = form
        if not request.GET.get('get') == '1':
            channel_id = self.kwargs.get('channel_id')
            return redirect('/channel/%s/' % channel_id)
        return self.render_to_response(context)

    def get_success_url(self, *args, **kwargs):
        channel_id = self.kwargs.get('channel_id')
        return '/channel/%s/' % channel_id

    def form_valid(self, form, **kwargs):
        channel_id = self.kwargs.get('channel_id')
        channel = Channel.objects.get(pk=channel_id)
        # If we don't have a file we can't have an md5 of file
        if form.files.get('file'):
            hash_value = hashlib.md5(form.files.get('file').read()).hexdigest()
            file_type = form.files.get('file').content_type
        else:
            hash_value = None
            file_type = None
        new_location = form.save(commit=False)
        new_location.channel = Channel.objects.get(pk=channel_id)
        new_location.md5 = hash_value
        new_location.file_type = file_type
        new_location.updated_by = self.request.user
        new_location.language_code = self.request.LANGUAGE_CODE.lower()
        new_location.save()
        form.save_m2m()

        # Save the creation to the database log
        log = LocationLog(user=self.request.user,
                          location_id=new_location.id,
                          type='created')
        log.save()

        return super(AddLocation, self).form_valid(form)

    def form_invalid(self, form):
        """
        If the form is invalid, re-render the context data with the
        data-filled form and errors.
        """
        channel_id = self.kwargs.get('channel_id')
        channel = Channel.objects.get(pk=channel_id)
        locations = get_locations(self.request.user.username,
                                  channel,
                                  self.request.LANGUAGE_CODE)
        context = {
            'locations': locations,
            'channel': channel,
            'form': form,
        }
        return render(self.request, 'channel/detail.html', context)


# Edit a location, pass in a form instance of the requested location to
# make changes to.
class EditLocation(UpdateView):
    form_class = LocationForm
    model = Location
    template_name = 'channel/edit_location.html'

    def get_object(self, queryset=None):
        obj = get_object_or_404(Location, pk=self.kwargs['location_id'])
        return obj

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        location_id = self.kwargs.get('location_id')
        location = Location.objects.get(pk=location_id)
        # If user is staff or last updated the location allow them to edit
        if request.user.is_staff or location.updated_by == request.user:
            return super(EditLocation, self).dispatch(request, *args, **kwargs)

        return HttpResponseForbidden()

    def get_success_url(self, *args, **kwargs):
        channel_id = self.kwargs.get('channel_id')
        return '/channel/%s/' % channel_id

    def get_context_data(self, **kwargs):
        channel_id = self.kwargs.get('channel_id')
        context = super(EditLocation, self).get_context_data(**kwargs)
        context['channel'] = Channel.objects.get(pk=channel_id)
        return context

    def form_valid(self, form):
        location = form.instance

        # if have a new file reset the md5 and file type
        # otherwise handled automagically
        if form.files.get('file'):
            hash_value = hashlib.md5(form.files.get('file').read()).hexdigest()
            file_type = form.files.get('file').content_type
            location.md5 = hash_value
            location.file_type = file_type

        elif 'file-clear' in self.request.POST:
            location.md5 = None
            location.file_type = None

        location.updated_by = self.request.user
        location.updated = timezone.make_aware(
            datetime.datetime.today(),
            timezone.get_current_timezone())
        location.save()

        # Save the deletion to the database log
        log = LocationLog(user=self.request.user,
                          location_id=location.id,
                          type='edited')
        log.save()

        return super(EditLocation, self).form_valid(form)


# Remove a location from the db.
@login_required
def remove_location(request, channel_id, location_id):
    channel = Channel.objects.get(pk=channel_id)
    location = get_object_or_404(Location, pk=location_id)

    # Save the deletion to the database log
    log = LocationLog(user=request.user,
                      location_id=location.id,
                      type='deleted')
    log.save()

    location.delete()
    # to do - make sure delete the actual file in the directory at this point
    return HttpResponse('successful delete')


# Edit the channel settings, only staff can use these.
# Updates the channel when a change is made.
@staff_member_required
@login_required
def edit_channel(request, channel_id):
    channel = Channel.objects.get(pk=channel_id)
    if request.method == 'POST':
        form = ChannelForm(request.POST, instance=channel)

templates/channel/channel.html
{% extends 'base.html' %}
{% load l10n %}

{% block action %}{% url 'channel:index' %}{% endblock %}

{% block method %}POST{% endblock %}

{% block pagetitle %}

	<div class="col-sm-12"><h2 class="align-center">{% trans "Select a channel." %}</h2></div>

{% endblock %}

{% block js %}
	{% if not form.title.errors or form.description.errors %}
		$('.channel').hide();
	{% endif %}
	$(document).on('click', '.add-channel', function(e) {
		e.preventDefault();
		$('.channel').slideToggle('fast', function(){ $('#id_title').focus(); });
		$('.fa-plus').toggleClass('fa-minus')
	});

{% endblock %}

{% block main-content %}

	{% csrf_token %}

	<div class="channel-page">

		<div class="row">
			<div class="col-sm-12">
				{% if user.is_staff %}
				<div class="row">
					<div class="col-sm-12 add-channel-button">
						<a href="{% url 'channel:index' %}" class="add-channel">
							<div class="channel-style add-channel-style">
								<h3>{% trans "Add a new channel" %}</h3>
								<i class="fa fa-5x fa-plus pull-right"></i>
								<h4>{% trans "A channel is a collection of locations and media to show at once." %}</h4>
								<h4>{% trans "Click here to create a new channel for locations." %}</h4>
								<div class="clear"></div>
							</div>
						</a>
						<div class="channel col-sm-8 col-sm-offset-2">
							{{form.title}}
							{% if form.title.errors %}
								<div class="bs-callout bs-callout-danger">
									{{form.title.errors.as_text|cut:"* "}}
								</div>
							{% endif %}

							{{form.description}}
							{% if form.description.errors %}
								<div class="bs-callout bs-callout-danger">
									{{form.description.errors.as_text|cut:"* "}}
								</div>
							{% endif %}

							{{form.centre_latitude}}
							{% if form.centre_latitude.errors %}
								<div class="bs-callout bs-callout-danger">
									{{form.centre_latitude.errors.as_text|cut:"* "}}
								</div>
							{% endif %}

							{{form.centre_longitude}}
							{% if form.centre_longitude.errors %}
								<div class="bs-callout bs-callout-danger">
									{{form.centre_longitude.errors.as_text|cut:"* "}}
								</div>
							{% endif %}

							{{form.radius}}
							{% if form.radius.errors %}
								<div class="bs-callout bs-callout-danger">
									{{form.radius.errors.as_text|cut:"* "}}
								</div>
							{% endif %}


							<input type="submit" value="{% trans "Submit" %}" class="btn-block submit-btn" />
						</div>
					</div>
				</div>
				{% endif %}
				<div class="row">
					{% for channel in channels %}
						<div class="col-sm-12">
							<a href="{% url 'channel:detail' channel.id %}"><div class="channel-style">
								<h3>{{ channel.title }}</h3>
								<i class="fa fa-5x fa-arrow-circle-o-right pull-right"></i>
								<h4>{% trans "Description" %}: {{ channel.description|truncatechars:140 }}</h4>
							</div></a>
						</div>
					{% endfor %}
				</div>
			</div>

			
		</div>
	</div>


{% endblock  %}

templates/channel/location_form.html
{% load i18n %}
<div id='popup-close'>X</div>

	{{form.title}}

	{{form.file}}

	{{form.description}}

	<div class="hide">
	{{form.latitude}}
	</div>
	<div class="hide">
	{{form.longitude}}
	</div>
	{{form.name}}
	{{ form.language_code.as_hidden }}

	<input  class='btn' type="submit" value="{% blocktrans %}Add Location{% endblocktrans %}" class="submit-btn btn-block" />

templates/channel/map.html
{% load l10n %}
<script id="mapjs" type="text/javascript">

{% load staticfiles %}
	var image = '{% static "images/placeholder.png" %}';
	var image_bw = '{% static "images/placeholder_bw.png" %}';
	var image_museon = '{% static "images/m_logo_sml.png" %}';

	function clickEvent(map, event){
		// Hide the preview box and remove the green marker
		$('#preview').hide();
		$('#gmap').gmap3({clear: 'currentmarker'});

		$('#addlocation').removeClass('hide');
		$('#id_title').focus();

		// If the map has been clicked before, remove the old green marker and put a new one here
		$('#gmap').gmap3({
			clear: {
				name: 'marker',
				tag: ['currentmarker']
			}
		});

		{% if user.is_authenticated %}
		// Add the new green marker indicating this is where the user has clicked
        $('#gmap').gmap3({
            action: 'addMarker',
            marker:{
                latLng: event.latLng,
                tag: ['currentmarker'],
                options: {
                	// do not allow to be dragable or will have to test if dragged outside of bounds
                    draggable: false,
                    icon: "http://maps.google.com/mapfiles/marker_green.png"
                },
                name: 'currentmarker',
            }
        });
		{% endif %}

		// Send the click location details to the form
        var lat = event.latLng.lat();
        var lng = event.latLng.lng();
		{% if user.is_authenticated %}
			$('#preview').load("/channel/1/add/?get=1", function(){
				$('#id_latitude').val(lat);
				$('#id_longitude').val(lng);
				// add function to make pop-up close button work
				$('#popup-close').click(function(e)
				{
					$('#preview').hide('fast');
				});
			});
            $('#preview').show();

        {% endif %}

		return;
	}


    // Destroy the initial map to refresh locations and create a new element
    $('#gmap').gmap3({
        action: 'destroy'
    });

    var remove_poi = [
                      {
                        "featureType": "poi",
                        "elementType": "labels",
                        "stylers": [
                          { "visibility": "off" }
                        ]
                      },
                      {
                          "featureType": "transit",
                          "elementType": "labels",
                          "stylers": [
                            { "visibility": "off" }
                          ]
                        }
                    ];

    $('#gmap').remove();
    $('.map-container').prepend('<div id="gmap"></div>');
	{% if channel.radius != None and channel.radius != 0 %}
	// if we have a radius limit points to the radius
	$('#gmap').gmap3({
  		// add bounds in a circle
  		circle:{
    		options:{
      			center: [{{latitude}}, {{longitude}}],
      			radius : {{radius}},
      			fillOpacity:0,
				strokeColor : "#FF4000"
    		},
    		events: {
    			click: function(map, event){
    				clickEvent(map, event);
    			},
    		}, //end events
    	},
   	});
   	{% endif %}

    // Initialise the google map with options, locations, and mouse events
    $('#gmap').gmap3({
        map:{

            // Set the initial options
            options:{
                center:[{{latitude}}, {{longitude}}],
                {% if channel.radius == 0 or channel.radius == None %}
                zoom:14,
                {% else %}
                zoom:12,
                {% endif %}
                zoomControl:true,
				zoomControlOptions: {
				    style:google.maps.ZoomControlStyle.LARGE
				},
                streetViewControl: false,
                mapTypeId: google.maps.MapTypeId.TERRAIN,
                mapTypeControl: false,
                mapTypeControlOptions: {
                    style: google.maps.MapTypeControlStyle.DROPDOWN_MENU
                },
                navigationControl: true,
                scrollwheel: true,
            },
			{% if channel.radius == 0 or channel.radius == None %}
			// if we have do not have a radius allow to add markers anywhere on map
            // Set the behaviour for mouse events
            events: {
                drag: function() {
                    $('#preview').hide();
                },

                click: function(map, event){
                	clickEvent(map, event);
                },

            }
            {% endif %}
        },

        // Create markers for all the locations stored in the db for this channel
        {% if locations %}
            marker:{
            	values:[
                    {% for location in locations %}
                    {
                        latLng:[{{location.latitude}}, {{location.longitude}}], 
                        data:"{{location.title}}",
                        {% if location.is_fixed %}
                        	{% if location.is_viewed %}
                        		// if permanent point (no location id) use the logo
                        		options:{icon:image},
                        	{% else %}
                        		// if permanent point (no location id) use the logo
                        		options:{icon:image_bw},
                        	{% endif %}
                        {% elif location.updated_by.is_staff %}
                        	options:{icon:image_museon},
                        {% elif location.updated_by.id == user.id %}
                        	// if point created by this user - make green
                        	options:{icon:"http://maps.google.com/mapfiles/marker_green.png"},
                        {% elif location.id %}
                        	// if user generated point show red marker
                        	options:{icon:"http://maps.google.com/mapfiles/marker.png"},
                        {% endif %}
                        // Create a unique tag for use with removing markers
                        tag: ['marker{{location.id}}'],
                        events:{
                            // Behaviour for clicking on a created marker
                            click: function() {
                                $(this).gmap3({
                                    clear: {
                                        name: 'marker',
                                        tag: ['currentmarker']
                                    }
                                });

                                // Centre the map on this location when clicked
                                $('#gmap').gmap3('get').setCenter(new google.maps.LatLng({{location.latitude}},{{location.longitude}}));
                                var preview_box = "<div id='popup-close'>X</div><h5 class='align-center'>{{ location.title }}</h5><div class='preview-media align-center'>";
								{% if location.file and location.file_type and 'image/' in location.file_type %}
                                	preview_box += "<img src='{{location.file.url}}' />";
                                {% elif location.file and location.file_type and 'video/' in location.file_type %}
                                	preview_box += "\
                                	 <video controls><source src='{{ location.file.url }}' type='{{ location.file_type }}'>Your browser does not support the video element.</video>";
                                {%elif location.file and location.file_type and 'audio/' in location.file_type %}
                                	preview_box += "\
                                 	<audio controls><source src='{{ location.file.url }}' type='{{ location.file_type }}'>Your browser does not support the audio element.</audio>";
                                {% else %}
                                	//nothing
                                {% endif %}
                                	preview_box += "{{ location.description|escapejs }}<br/>";
                                {% if location.name %}
                                	preview_box += "<i>{{ location.name|escapejs }}</i><br/>";
                                {% endif %}
                                {% if location.updated_by.id == user.id or user.is_staff %}
	                                preview_box += "<a class='btn btn-danger delete-button' href='{% url 'channel:remove_location' channel.id location.id %}' data-location='{{location.latitude}},{{location.longitude}}'>{% blocktrans %}Remove Location{% endblocktrans %}</a>";
                                {% endif%}
                                preview_box += "</div>";
                                $('#preview').html(preview_box);
                                $('#preview').show();
								// add function to make close button close
								$('#popup-close').click(function(e)
								{
									$('#preview').hide('fast');
								});
                            }
                        }
                    }{% if not forloop.last %},{% endif %}
                    {% endfor %}
               
                ],
            }
        {% endif %}

    });

    $('#gmap').gmap3('get');
    $('#gmap').gmap3('get').setOptions({styles: remove_poi});

</script>

templates/channel/view_locations.html
{% extends 'base.html' %}
{% load l10n %}

{% block js %}

	$(document).on('click', '.delete-button', function(e) {
		var url = $(this).attr('href');
		$obj = $(this);
		
		e.preventDefault();
		$.get(url, function(obj) {
			$obj.closest('.single-location').slideUp('normal', function() { $(this).remove(); });
		});
	});

{% endblock %}

{% block pagetitle %}

<div class="ribbon-container-left">
	<a href="{% url 'channel:detail' channel.id %}">
	<i class="fa fa-fw fa-arrow-circle-o-left"></i> {% trans "Add Locations" %}</a>
</div>

<h2 class="align-center pagetitle">{% trans "View and edit your added locations" %}</h2>


{% endblock %}

{% block main-content %}

	{% csrf_token %}

	<div class="view-locations">
		<div class="col-sm-12">
			{% for location in locations %}
				<div class="row single-location" data-tag="marker{{location.id}}">
					<div class="col-sm-8">
						
							<h4>{{ location.title }}</h4>
							<h4>{% trans "description:" %} {{location.description}}</h4>
							<h4>{% trans "language code:" %} {{location.language_code}}</h4>{% trans "written by:" %}<i>{{location.name}}</i>
							<h4>file: {% if location.file %}<a href="{{ location.file.url }}">{{ location.file }}</a>{% else %}(none){% endif %}</h4>

					</div>
					<div class="col-sm-4">
					{% if location.updated_by.id == user.id or user.is_staff %}
						<a class="btn btn-link edit-button" href="{% url 'channel:edit_location' channel.id location.id %}">{% trans "Edit" %}</a>

						<a class="btn btn-link pull-right delete-button" href="{% url 'channel:remove_location' channel.id location.id %}">{% trans "Delete" %}</a>
					{% endif %}
					</div>
				</div>

			{% endfor %}	
		</div>
	</div>

{% endblock %}